Droll Ash Nuthatch

High

# Vault::externalCall doesnâ€™t check for execution success

## Summary

`externalCall.call` execution `success` is not checked.

## Vulnerability Detail

`Vault:externalCall` makes a call to passed data, but the function called may not succeed and this is not checked, assuming all calls execute perfectly and without returns.

```solidity
function externalCall(
    address to,
    bytes calldata data
) external nonReentrant returns (bool success, bytes memory response) {
    _requireAtLeastOperator();
    if (configurator.isDelegateModuleApproved(to)) revert Forbidden();
    IValidator validator = IValidator(configurator.validator());
    validator.validate(
        msg.sender,
        address(this),
        abi.encodeWithSelector(msg.sig, to, data)
    );
    validator.validate(address(this), to, data);
    (success, response) = to.call(data); // @audit missing success check
    emit ExternalCall(to, data, success, response);
}
```

## Impact

If the function called via `call` fails, execution of `Vault:externalCall` will continue, assuming always the low-level call was succeeded.

## Code Snippet

https://github.com/sherlock-audit/2024-06-mellow/blob/26aa0445ec405a4ad637bddeeedec4efe1eba8d2/mellow-lrt/src/Vault.sol#L262

## Tool used

Manual Review

## Recommendation

Add check if `success` is true.